name: Label PRs Automatically

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write   
    steps:
      - name: Add label to Pull Request
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            needs review
